apiVersion: v1
kind: Pod
metadata:
        name: student-entry
        labels:
                app: student-entry
spec:
        containers:
                - name: student-entry
                  image: vaishnavi2131/postgres-java-app:latest
                  ports:
                          - containerPort: 8081
                  env:
                          - name: DB_URL
                            value: "jdbc:postgresql://my-release-postgresql.default:5432/parth123"
                          - name: DB_USER
                            value: "parth"
                          - name: DB_PASS
                            value: "parth4321"
                            
                
