apiVersion: v1
kind: Pod
metadata:
        name: student-entry
        labels:
                app: student-entry
spec:
        containers:
                - name: student-entry
                  image: vaishnavi2131/student-entry:latest
                  ports:
                          - containerPort: 8081
                  env:
                          - name: DB_URL
                            valueFrom:
                                secretKeyRef:
                                        name: db-credentials
                                        key: DB_URL
                          - name: DB_USER
                            valueFrom:
                                secretKeyRef:
                                        name: db-credentials
                                        key: DB_USER
                          - name: DB_PASS
                            valueFrom:
                                secretKeyRef:
                                        name: db-credentials
                                        key: DB_PASS
                            
                
