apiVersion: v1
kind: Pod
metadata:
        name: student-entry
        labels:
                app: student-entry
spec:
        containers:
                - name: student-entry
                  image: vaishnavi2131/student-entry:latest
                  ports:
                          - containerPort: 8081
                            
                
